vim.api.nvim_create_user_command('Annoy', function()
  vim.api.nvim_command('echo "Annoying!"')
  vim.api.nvim_command('Precognition show')
  vim.api.nvim_command('Hardtime enable')
end, {})

vim.api.nvim_create_user_command('Unannoy', function()
  vim.api.nvim_command('echo "Stop Annoying!"')
  vim.api.nvim_command('Precognition hide')
  vim.api.nvim_command('Hardtime disable')
end, {})
